# Generated by Django 5.2.4 on 2025-07-31 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0003_skincareprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('Dry', 'Dry'), ('Oily', 'Oily'), ('Normal', 'Normal'), ('Combination', 'Combination')], max_length=20)),
                ('sensitivity', models.BooleanField(default=False)),
                ('concerns', models.TextField(help_text='List skin concerns like acne, dryness, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
