name: Deploy SkinPal

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: skinpal_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: skinpal_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U skinpal_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://skinpal_user:password@localhost:5432/skinpal_db
        run: python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://skinpal_user:password@localhost:5432/skinpal_db
        run: python manage.py test
